[project]
name = "mics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "econml>=0.16.0",
    "ipykernel>=6.31.0",
    "lightgbm>=4.6.0",
    "matplotlib>=3.9.4",
    "scikit-learn>=1.6.1",
]
